"use client"

import Image from "next/image"

const tools = [
  { name: "Bolt", src: "/logos/bolt.png", invert: true },
  { name: "v0", src: "/logos/v0.png", invert: true },
  { name: "Lovable", src: "/logos/lovable.png", invert: false },
  { name: "Cursor", src: "/logos/cursor.png", invert: false },
  { name: "Replit", src: "/logos/replit.png", invert: false },
  { name: "Windsurf", src: "/logos/windsurf.png", invert: true },
  { name: "Tempo", src: "/logos/tempo.png", invert: true },
  { name: "Warp", src: "/logos/warp.png", invert: false },
  { name: "Claude", src: "/logos/claude.png", invert: true },
]

function ShieldIcon({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 120 140"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M60 5L10 25V65C10 95 30 120 60 135C90 120 110 95 110 65V25L60 5Z"
        stroke="currentColor"
        strokeWidth="6"
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
      />
      <path
        d="M40 70L55 85L85 55"
        stroke="#4ade80"
        strokeWidth="8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#09090B] text-white">
      {/* Hero Section */}
      <main className="flex flex-col items-center justify-center min-h-screen px-6 py-20">
        {/* Shield Icon */}
        <div className="mb-12">
          <ShieldIcon className="w-32 h-32 md:w-40 md:h-40 text-white" />
        </div>

        {/* Headline */}
        <h1 className="text-4xl md:text-6xl lg:text-7xl font-semibold text-center max-w-4xl leading-tight tracking-tight">
          Scan your AI-built app
          <br />
          <span className="text-[#4ade80]">before you ship</span>
        </h1>

        {/* Subheadline */}
        <p className="mt-6 text-lg md:text-xl text-zinc-400 text-center max-w-2xl">
          VibeShield finds security vulnerabilities in code generated by AI coding tools and helps you fix them instantly.
        </p>

        {/* CTA Button */}
        <button className="mt-10 px-8 py-4 bg-white text-black font-medium rounded-full text-lg hover:bg-zinc-200 transition-colors">
          Start Free Scan
        </button>

        {/* Tools Section */}
        <div className="mt-20 flex flex-col items-center">
          <p className="text-sm text-zinc-500 mb-8 uppercase tracking-wider">
            Works with code from
          </p>
          <div className="flex flex-wrap justify-center items-center gap-8 md:gap-12 max-w-4xl">
            {tools.map((tool) => (
              <div
                key={tool.name}
                className="w-10 h-10 md:w-12 md:h-12 flex items-center justify-center opacity-60 hover:opacity-100 transition-opacity"
              >
                <Image
                  src={tool.src}
                  alt={tool.name}
                  width={48}
                  height={48}
                  className={`object-contain w-full h-full ${tool.invert ? "invert" : ""}`}
                />
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}
