import type { PatchSuggestion, ScanFinding, ScanReport } from "./types"

export function getRiskLabel(score: number) {
  if (score <= 19) return "Low"
  if (score <= 49) return "Moderate"
  if (score <= 79) return "Action required"
  return "Critical"
}

export function calculateRiskScore(findings: Pick<ScanFinding, "severity">[]) {
  const score = findings.reduce((total, finding) => {
    if (finding.severity === "critical") return total + 25
    if (finding.severity === "high") return total + 15
    if (finding.severity === "medium") return total + 7
    if (finding.severity === "low") return total + 3
    return total + 1
  }, 0)

  return Math.min(100, score)
}

export function createDeterministicPatch(finding: ScanFinding): PatchSuggestion | undefined {
  if (!finding.patchable) return undefined

  if (finding.category === "input_validation") {
    return {
      title: "Validate request body with Zod",
      summary:
        "Add a route-specific schema based on the actual request contract and parse the JSON body before any business logic uses it.",
      reviewRequired: true,
    }
  }

  if (finding.category === "missing_auth") {
    return {
      title: "Add a server-side auth guard",
      summary:
        "Use the project's real authentication provider to verify the user on the server, then enforce role or ownership checks before returning sensitive data.",
      reviewRequired: true,
    }
  }

  if (finding.category === "ai_endpoint_risk") {
    if (/execution bounds|tool-calling/i.test(finding.title)) {
      return {
        title: "Bound AI tool execution",
        summary:
          "Add explicit tool-call step limits, token limits, and per-user quota/budget checks before allowing the model to invoke tools.",
        reviewRequired: true,
      }
    }

    return {
      title: "Add rate limiting before model calls",
      summary:
        "Insert the project's real quota, rate-limit, bot protection, and budget checks before the first model invocation in this route.",
      reviewRequired: true,
    }
  }

  if (finding.category === "public_env_misuse") {
    return {
      title: "Move public secret to server-only environment variable",
      summary: "Rename the variable without NEXT_PUBLIC_ and read it only from server code.",
      reviewRequired: true,
    }
  }

  if (finding.category === "secret_exposure") {
    return {
      title: "Remove committed secret and rotate it",
      summary: "Delete the committed value, rotate the credential, and load it from server-only environment variables.",
      before: finding.evidence,
      reviewRequired: true,
    }
  }

  if (finding.category === "unsafe_tool_calling" || finding.category === "mcp_risk") {
    return {
      title: "Replace dynamic tool dispatch with an allowlist",
      summary:
        "Define the exact tools this route is allowed to call, validate the requested name against that fixed set, and reject anything outside it before dispatch.",
      reviewRequired: true,
    }
  }

  return undefined
}

export function filterReportFindings(report: ScanReport, findingIds?: string[]) {
  if (!findingIds || findingIds.length === 0) return report

  const allowed = new Set(findingIds)
  const findings = report.findings.filter((finding) => allowed.has(finding.id))
  return {
    ...report,
    riskScore: calculateRiskScore(findings),
    findings,
  }
}

export function generateIssueBody(report: ScanReport, findingIds?: string[]) {
  const scopedReport = filterReportFindings(report, findingIds)
  const topFindings = [...scopedReport.findings]
    .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
    .slice(0, 10)

  const lines = [
    "# VibeShield security scan",
    "",
    `**Project:** ${scopedReport.projectName}`,
    `**Source:** ${scopedReport.sourceLabel}`,
    `**Risk score:** ${scopedReport.riskScore}/100 (${getRiskLabel(scopedReport.riskScore)})`,
    `**Files inspected:** ${scopedReport.filesInspected}`,
    `**Findings included:** ${scopedReport.findings.length} of ${report.findings.length}`,
    "",
    "## Top findings",
    "",
    ...topFindings.flatMap((finding) => [
      `- **${finding.severity.toUpperCase()}** ${finding.title}`,
      `  - File: \`${formatFindingLocation(finding)}\``,
      `  - Category: \`${finding.category}\``,
      `  - Recommendation: ${finding.recommendation}`,
    ]),
    "",
    "## Recommended next steps",
    "",
    "1. Rotate any exposed credentials and remove committed `.env` files.",
    "2. Add server-side auth guards to sensitive API routes.",
    "3. Add rate limits and abuse controls before AI model calls.",
    "4. Validate request bodies with schemas before using user input.",
    "5. Review generated patch suggestions before applying them.",
    "",
    "_Generated by VibeShield._",
  ]

  return lines.join("\n")
}

function formatFindingLocation(finding: ScanFinding) {
  if (!finding.lineStart) return finding.filePath
  return `${finding.filePath}:${finding.lineStart}`
}

function severityRank(severity: ScanFinding["severity"]) {
  if (severity === "critical") return 5
  if (severity === "high") return 4
  if (severity === "medium") return 3
  if (severity === "low") return 2
  return 1
}
