import { sanitizePublicPullRequestCopy } from "@/lib/ai/publicPullRequestCopy"
import type { PullRequestSafetyReviewOutput } from "@/lib/ai/structuredSchemas"

export type PullRequestSafetyDraft = {
  title: string
  body: string
}

export type PullRequestSafetyResult = {
  approved: boolean
  title?: string
  body?: string
  summary?: string
  blockingReasons?: string[]
  requiredChanges?: string[]
  model?: string
  provider?: string
  error?: string
}

const UNSAFE_PUBLIC_PR_COPY_RE =
  new RegExp(String.raw`\b(Badger|${["Vibe", "Shield"].join("")}|localhost|127\.0\.0\.1|\/api\/scan|scan id|scan metadata|security scanner|static analysis report|auto-generated|generated by|generated from|Stop Claude|ignore previous instructions)\b`, "i")

export function applyPullRequestSafetyDecision(
  draft: PullRequestSafetyDraft,
  decision: PullRequestSafetyReviewOutput,
): PullRequestSafetyResult {
  if (decision.decision === "block") {
    return blockedResult(decision, "Claude safety review blocked this pull request.")
  }

  const candidate = decision.decision === "revise"
    ? {
        title: decision.revisedTitle ?? draft.title,
        body: decision.revisedBody ?? draft.body,
        reportMarkdown: "",
      }
    : {
        title: draft.title,
        body: draft.body,
        reportMarkdown: "",
      }

  const sanitized = sanitizePublicPullRequestCopy(candidate)
  const all = `${sanitized.title}\n${sanitized.body}`
  if (!decision.approved && decision.decision !== "revise") {
    return blockedResult(decision, "Claude safety review did not approve this pull request.")
  }

  if (!sanitized.title || !sanitized.body || UNSAFE_PUBLIC_PR_COPY_RE.test(all)) {
    return blockedResult(decision, "Claude safety review could not produce clean public pull request copy.")
  }

  return {
    approved: true,
    title: sanitized.title,
    body: sanitized.body,
    summary: decision.summary,
    blockingReasons: decision.blockingReasons ?? [],
    requiredChanges: decision.requiredChanges ?? [],
  }
}

function blockedResult(decision: PullRequestSafetyReviewOutput, fallback: string): PullRequestSafetyResult {
  return {
    approved: false,
    summary: decision.summary,
    blockingReasons: decision.blockingReasons ?? [],
    requiredChanges: decision.requiredChanges ?? [],
    error: `${fallback}${decision.blockingReasons?.length ? ` ${decision.blockingReasons.join(" ")}` : ""}`,
  }
}
